version: "3.9"
services:
  redis:
    container_name: Xeltpy-Redis-Dev
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - dev_redis_volume:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  dev_redis_volume: