[tool.poetry]
name = "xelt.py"
version = "3.0.0"
description = "Xelt is a multi-purpose discord bot with features ranging from user information to music!"
authors = ["No767, Edqe14, ThEditor"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<4"
discord-py = {extras = ["voice"], version = "^2.1.0"}
python-dotenv = "^0.21.0"
aiodns = "^3.0.0"
brotli = "^1.0.9"
uvloop = "^0.17.0"
psutil = "^5.9.4"
prisma = "^0.8.0"
orjson = "^3.8.5"
ormsgpack = "^1.2.4"
coredis = "^4.10.2"
ciso8601 = "^2.3.0"
rich = "^13.1.0"
anyio = "^3.6.2"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.21.0"
pytest = "^7.2.1"
pytest-asyncio = "^0.20.3"
mypy = "^0.991"
pyright = "^1.1.286"
types-psutil = "^5.9.5.5"
tox = "^4.2.6"
pyinstrument = "^4.4.0"

[tool.isort]
profile = 'black'

[tool.pyright]
include = ["bot/**"]
exclude = ["**/__pycache__", "**/.mypy_cache", "**/.dmpypy.json"]
ignore = ["docker"]
reportMissingImports = true
reportMissingTypeStubs = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
