#!/usr/bin/env bash

XELT_FIRST_START_CHECK="XELT_FIRST_START"

if [ ! -f $XELT_FIRST_START_CHECK ]; then
    touch $XELT_FIRST_START_CHECK
    echo "DO NOT EDIT THIS FILE! THIS IS USED WHEN YOU FIRST RUN XELT USING DOCKER!" >> $XELT_FIRST_START_CHECK
    python3 /xelt/bot/migrations.py init
fi

exec python3 /xelt/bot/launcher.py