name: Docker Build

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - dev/v3
    tags:
      - 'v*'

jobs:
  Build-GHCR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/xeltbot/xelt.py
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=edge,branch=dev/v3

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3.2.1
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-ghcr-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-ghcr-
            
      - name: Build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new-ghcr

      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new-ghcr /tmp/.buildx-cache